### ISSUE TITLE
actualizar marcadores por defecto

### ISSUE THREAD

**Issue by ftoledo** [HuayraLinux/firefox-installer#2]
Cambiar los marcadores de la barra por defecto por url validas.

**Comment by matiasdelellis** [comment]
@ftoledo 
Fer, esto entiendo que ya esta ok.. pero probando note que en el primer inicio, muestra la pagina de bienvenida de Mozilla...

Para que no se muestre hay que agregrar:
```
[preferences]
...
...
browser.aboutwelcome.enabled=false
startup.homepage_welcome_url=""
```
